#!/usr/bin/env node
/**
 * figma-push.js
 *
 * Screenshots index.html and creates a frame in your Figma file.
 *
 * Usage:
 *   1. npm install puppeteer          (one-time)
 *   2. node figma-push.js             (run from repo root)
 *   3. Open Figma > TP-Inc. file
 *      Plugins > Development > Open Console
 *      Paste the contents of figma-snippet.js and hit Enter
 */

import puppeteer from 'puppeteer';
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const INDEX_HTML = resolve(__dirname, 'index.html');
const VIEWPORT   = { width: 1440, height: 900 };
const SCREENSHOT = resolve(__dirname, 'homepage-screenshot.png');
const SNIPPET    = resolve(__dirname, 'figma-snippet.js');

async function main() {
  console.log('Launching browser…');
  const browser = await puppeteer.launch({ headless: 'new' });
  const page    = await browser.newPage();

  await page.setViewport(VIEWPORT);
  await page.goto(`file://${INDEX_HTML}`, { waitUntil: 'networkidle0' });

  // Let web-font animations settle
  await new Promise(r => setTimeout(r, 800));

  console.log('Taking screenshot…');
  const screenshotBuffer = await page.screenshot({ path: SCREENSHOT, type: 'png', fullPage: false });
  await browser.close();

  const base64 = readFileSync(SCREENSHOT).toString('base64');
  console.log(`Screenshot saved → ${SCREENSHOT}`);

  // ── Generate Figma console snippet ──────────────────────────────────────
  const snippet = `
// Auto-generated by figma-push.js — paste into Figma > Plugins > Development > Open Console
(async () => {
  const base64 = "${base64}";
  const bytes  = Uint8Array.from(atob(base64), c => c.charCodeAt(0));
  const image  = figma.createImage(bytes);

  const frame  = figma.createFrame();
  frame.name   = "Homepage — TPI";
  frame.resize(${VIEWPORT.width}, ${VIEWPORT.height});
  frame.fills  = [{ type: 'IMAGE', imageHash: image.hash, scaleMode: 'FILL' }];

  figma.currentPage.appendChild(frame);
  figma.viewport.scrollAndZoomIntoView([frame]);
  console.log('✓ Frame created:', frame.name);
})();
`.trim();

  writeFileSync(SNIPPET, snippet);
  console.log(`\nFigma snippet saved → ${SNIPPET}`);
  console.log('\nNext steps:');
  console.log('  1. Open Figma and navigate to your TP-Inc. file');
  console.log('  2. Go to  Plugins > Development > Open Console');
  console.log('  3. Paste the contents of figma-snippet.js and press Enter');
  console.log('  4. A "Homepage — TPI" frame will appear on the current page');
}

main().catch(err => { console.error(err); process.exit(1); });
